### ISSUE TITLE
Field values containing the colon character are parsed incorrectly

### ISSUE THREAD

**Issue by Rua-Yuki** [FGRibreau/node-redis-info#21]
**Node version:** 10.19.0
**redis-info version**: 3.0.7

---

The current key-value parsing logic results in incorrect outputs being produced when given fields containing the colon character within their value.

For example, given an `INFO` response with:
```yaml
# Server
config_file:Y:\redis\redis.conf
```

The resulting object generated from parsing this data would be:
```js
{
  databases: {},
  commands: {},
  config_file: 'Y'
}
```

Observe how the `config_file` value has been undesirably truncated, with everything following the initial colon being lost.

This is a result of key-value parsing logic assuming only two colon-delimited components (key and value) will exist:

https://github.com/FGRibreau/node-redis-info/blob/bfcc13cb43e6fa1a6978090fbbbedd6d7c7f2de5/index.js#L107

A simple solution would be to join all components following index 0 with `":"` and apply this value rather than only that at index 1.

**Comment by FGRibreau** [comment]
Thanks! Released in v3.0.8
